ALTER TABLE pets
  ADD COLUMN IF NOT EXISTS sterilized BOOLEAN DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS habitat TEXT,
  ADD COLUMN IF NOT EXISTS feeding TEXT,
  ADD COLUMN IF NOT EXISTS cohabitation BOOLEAN DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS cohabitation_details TEXT;
